# apt
alias sau="sudo apt update"
alias saug="sudo apt upgrade"
alias sai="sudo apt install"
alias sar="sudo apt remove"
alias saar="sudo apt autoremove"
alias sap="sudo apt purge"
alias sas="sudo apt search"
alias sal="sudo apt list"
alias sali="sudo apt list --installed"
alias saif="sudo apt info"

# snap
alias ssi="sudo snap install"
alias ssr="sudo snap remove"
alias ssl="sudo snap list"

# fastboot
alias fbre="fastboot reboot"
alias fbgc="fastboot getvar current-slot"
alias fbsa="fastboot set_active a"
alias fbsb="fastboot set_active b"
alias fbfa="fastboot flash boot_a"
alias fbfb="fastboot flash boot_b"

# file system
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# misc
alias e="exit"
